# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-05 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20180605_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '板块', 'verbose_name_plural': '板块'},
        ),
    ]
