# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100, verbose_name='消息内容')),
                ('link', models.CharField(max_length=500, verbose_name='跳转链接')),
                ('status', models.IntegerField(choices=[(0, '未读'), (-1, '已读')], default=0, verbose_name='消息状态')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='消息所属人')),
            ],
        ),
    ]
